### ISSUE TITLE
Proxy to backend?

### ISSUE THREAD

**Issue by skug67** [klinker-apps/pulse-sms-web#135]
Is there any chance that the web interface could act as a proxy to the backend instead of just providing the frontend template?  Sort of like what I gather can be done via an environment variable in the desktop client?  Would be a big help for those of us working behind a corporate firewall (and also prohibited from installing external desktop apps).

Thanks in advance (even if it turns out to not be possible).

**Comment by klinker24** [comment]
Sorry, no, that isn't something that is going to be possible with our desktop app.

**Comment by Serubin** [comment]
Following up - as someone who worked behind restrictive corporate proxies for years - the webapp in a browser will follow your browsers proxy guidance. 
There should be no need for additional proxy settings required. 

The chrome app and PWA should function the same.
