### ISSUE TITLE
Dup issue??? web app very slow at sending mesage.

### ISSUE THREAD

**Issue by mwsidwel** [klinker-apps/pulse-sms-web#139]
I understand and have read another issue stating the same thing I'm seeing but thought I'd bring it back up.

I have not upgrade android, windows, or the pulsesms app. All of the sudden about a week ago I started noticing that the web app was taking a long time for messages to go out.

If I send any type of message from the web app, it takes about 3 minutes to be sent out. If I send a message from the android app, the web shows it almost immediately. It seems its a one way communication issue.

I understand that the web app sends a push notification to tell the android app to send out the message. Does the same happen if a message is sent from the phone? Does the phone send a message through google to the web app to update it's data?

On the other issue documenting this someone from the web team said about the double checkmark "That action makes a data call, opening your phone to receive the push notification."  

Thats not the stated action of the double checkmark in the app. The app clearly states that it is used to mark all messages as read. That should not be opening a data call so I don't think that's a fix to getting the web app to send data to the phone. 

Could someone give a better explanation of what might be going on?

**Comment by klinker24** [comment]
The phone controls all SMS communication and all communication with your carrier. When you are sending a message from the phone app, Pulse simply passes the message to Android to be sent. 

All that the web app does is forward messages to your phone to be sent. It isn't as though my Pulse SMS service is actually sending the messages. The web app sends a push notification to your phone. When your phone receives that push notification, it pulls the message content out and passes it to the system to send the message.

If you see a delay in the messages being sent, then something is preventing the push notification from reaching your device. Pulse uses Google Play Services to send and receive these push notifications. Restarting the phone is a simple way to improve the reliability of Google Play Services. Unfortunately, my app has absolutely no control over how long the push notifications take to reach your device.

I think you are confused about the double checkmark and whatever other issue you looked at. The double checkmark does in fact make a data call. How else would the web app know that messages are marked as "read". That isn't relevant to this situation.
