### ISSUE TITLE
Domain renewal

### ISSUE THREAD

**Issue by andrefecto** [klinker-apps/pulse-sms-web#140]
This isn't an exactly an issue with the software itself but the domain seems to have expired. When you visit, you're met with a parked domain/renewal message.

**Comment by klinker24** [comment]
I am so sorry, somehow auto-renew got turned off on the domain. It is back up now, might take a few minutes for your computer to recognize it.

I don’t have a clue how that could have happened, I have had it for 2 years and it successfully renewed the first year. Really sorry for the trouble!

**Comment by andrefecto** [comment]
No problem! Just wanted to make sure it was brought up.
