### ISSUE TITLE
Feature Request: Option to Disable Web Links Previews

### ISSUE THREAD

**Issue by 8227846265** [klinker-apps/pulse-sms-web#143]
### Problem Description

On Pulse SMS Web and Android app. The links received on an SMS is automatically shown a preview by default.

However, for transactional SMS that embeds links to it. It only appears as a Spam.

Imagine:

**Sender: Your Bank**
**11:10 AM | SMS 1:** 
Your latest transaction worth XXXX. If you didn't do this transaction, you can ask for assistance at www.example.com

{Web Link Preview}
![image](https://user-images.githubusercontent.com/66582769/84617465-97831600-af01-11ea-9e10-2f5b6713bace.png)

**11:11 AM | SMS 2:** 
Your latest transaction worth XXXX. If you didn't do this transaction, you can ask for assistance at www.example.com

{Web Link Preview}
![image](https://user-images.githubusercontent.com/66582769/84617471-99e57000-af01-11ea-80ff-e0351df3b4c4.png)

**11:15 AM | SMS 3:** 
Your latest transaction worth XXXX. If you didn't do this transaction, you can ask for assistance at www.example.com

{Web Link Preview}
![image](https://user-images.githubusercontent.com/66582769/84617472-9baf3380-af01-11ea-8bad-874785cb7154.png)

On the Web, the web link preview eats space on the SMS view at least 800+ pixels in height.

On Android, I think it would be around 300+ pixels in height. Not sure but it's big as well.

### Proposed Solution

Provide an option in the Settings to disable web links previews on SMS globally.

Or it can be personalized wherein per contact or SMS Sender. You can disable web link previews

**Comment by Serubin** [comment]
Can you better define what you mean by "appears as spam?" I don't totally understand the issue as this functions as intended.

For whatever it's worth, web preview images are about 300~ pixels tall, total height for the message block is 320 pixels.

![image](https://user-images.githubusercontent.com/1234465/84617647-88aa4e00-ae84-11ea-85f7-b348f193f2a1.png)

**Comment by klinker24** [comment]
You can already disable these previews. Just open the phone app, go to advanced features, and disable the internal browser

https://messenger.klinkerapps.com/help
